version: '3.2'

services:
  influxdb:
    build: influxdb
    restart: always
    env_file: configuration.env
    ports:
      - '8096:8086'
      - '2003:2003'
#    volumes:
#      - influxdb_data:/var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    restart: always
    env_file: configuration.env
    depends_on:
      - influxdb
    ports:
      - '3002:3000'
    volumes:
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/datasources:/usr/share/grafana/datasources
#      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: {}
  influxdb_data: {}
